In [1]:
print("Welcome to Numpy-2")

Welcome to Numpy-2


# Agenda

- **Installing and Importing Numpy**✅
- **Introduction to use case**✅
- **Motivation: Why to use Numpy? - How is it different from Python Lists?**✅
- **Creating a Basic Numpy Array**✅
    - From a List - `array()`, `shape`, `ndim`✅
    - From a range and stepsize - `arange()`✅
    - `type()` ndarray✅
- **How numpy works under the hood?**✅
- **Indexing and Slicing on 1D** ✅
    - Indexing✅
    - Slicing✅
    - Masking (Fancy Indexing)✅
- **Operation on array**✅
- **Universal Functions (ufunc) on 1D array**✅
    - Aggregate Function/ Reduction functions - `sum()`, `mean()`, ✅`min()`, `max()`✅
- **Usecase: calculate NPS**✅
    - loading data: `np.loadtxt()`✅
    - `np.empty()`
    - `np.unique()`





In [2]:
import numpy as np

In [4]:
np.array([[1, 2, 3, 4], [6, 7, 8, 10]])

array([[ 1,  2,  3,  4],
       [ 6,  7,  8, 10]])

In [5]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
a[2]

3

In [7]:
a[-10]

3

In [ ]:
[2,3,6,8]

In [8]:
a[[2,3,6,8]]

array([3, 4, 7, 9])

In [9]:
a[[2,3,6,8,4,3,4,3,4,3,4,1,3,6,8]]

array([3, 4, 7, 9, 5, 4, 5, 4, 5, 4, 5, 2, 4, 7, 9])

In [ ]:
[-10,-9,-6,-4]

In [10]:
a[[-10,-9,-6,-4]]

array([3, 4, 7, 9])

In [13]:
# a[[1,2,16]]

In [ ]:
[2,3,-6,-4]

In [14]:
a[[2,3,-6,-4]]

array([3, 4, 7, 9])

In [16]:
a[[1,2,-3]]

array([ 2,  3, 10])

In [17]:
# a[2,3,-6]

In [ ]:
# Slicing

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
a[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
a[::]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
a[0:5]

array([1, 2, 3, 4, 5])

In [22]:
a[:5]

array([1, 2, 3, 4, 5])

In [24]:
a[2:7:1]

array([3, 4, 5, 6, 7])

In [25]:
a[2:7:2]

array([3, 5, 7])

In [26]:
a[2:7:-1]

array([], dtype=int64)

In [27]:
a[7:2:-1]

array([8, 7, 6, 5, 4])

In [28]:
a[-10:-3:1]

array([3, 4, 5, 6, 7, 8, 9])

In [29]:
a[-10:-3:-1]

array([], dtype=int64)

In [30]:
a[-4:-10:-2]

array([9, 7, 5])

In [31]:
a[8:-10:-2]

array([9, 7, 5])

In [32]:
a[-1]

12

In [33]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
a[-3::]=np.array([100,100,100])

In [36]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 100, 100, 100])

In [37]:
a[-3::]=np.array([101,102,103,104])

ValueError: could not broadcast input array from shape (4,) into shape (3,)

In [39]:
a[-3::]=1001

In [40]:
a

array([   1,    2,    3,    4,    5,    6,    7,    8,    9, 1001, 1001,
       1001])

In [41]:
a[-3::]=-10

In [42]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, -10, -10, -10])

In [44]:
a[2:7:2]=-1001

In [45]:
a

array([    1,     2, -1001,     4, -1001,     6, -1001,     8,     9,
         -10,   -10,   -10])

In [48]:
a[2:7:2]=5.9

In [49]:
a

array([  1,   2,   5,   4,   5,   6,   5,   8,   9, -10, -10, -10])

In [50]:
a=np.array([1.0,2.0,3.0,4.0,5.0,6.0,7.0])
a

array([1., 2., 3., 4., 5., 6., 7.])

In [52]:
a[:3]=5.9

In [53]:
a

array([5.9, 5.9, 5.9, 4. , 5. , 6. , 7. ])

In [54]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [55]:
b=np.array(a,dtype="float")
b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [56]:
# Masking

In [72]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [58]:
a+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
a<6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False])

In [60]:
a[a<6]

array([1, 2, 3, 4, 5])

In [61]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [62]:
a%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [63]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [64]:
a[a%5==0]

array([ 5, 10])

In [65]:
a[a%5==0]=100

In [66]:
a

array([  1,   2,   3,   4, 100,   6,   7,   8,   9, 100,  11,  12])

In [70]:
a[~(a%5==0)]=-1

In [71]:
a

array([-1, -1, -1, -1,  5, -1, -1, -1, -1, 10, -1, -1])

In [77]:
mask1 = (a%2==0)
mask2 = (a%5==0)
print(mask1)
print(mask2)

[False  True False  True False  True False  True False  True False  True]
[False False False False  True False False False False  True False False]


In [75]:
a[mask1 and mask2]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [76]:
a[mask1 or mask2]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [78]:
a[mask1 & mask2]

array([10])

In [79]:
a[mask1 | mask2]

array([ 2,  4,  5,  6,  8, 10, 12])

In [ ]:
a[mask1] and a[mask2]

In [80]:
a[mask1]

array([ 2,  4,  6,  8, 10, 12])

In [81]:
a[mask2]

array([ 5, 10])

In [82]:
a[mask1] and a[mask2] 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
mask1 = (a%2==0)
mask2 = (a%5==0)

In [85]:
# a[~(a<6)]

array([ 6,  7,  8,  9, 10, 11, 12])

In [ ]:
# a[a%2==0 & a%5==0 ] not recommended

In [86]:
a[(a%2==0) & (a%5==0) ]

array([10])

In [87]:
a[(a%2==0) & (a>4) ]

array([ 6,  8, 10, 12])

In [ ]:
np.array([1,2,3])
np.arrayrray

In [ ]:
a[(a%2==0) | (a>4)]

In [89]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([4,5,6,7])
print(a)
print(b)
print(c)


[1 2 3]
[4 5 6]
[4 5 6 7]


In [90]:
a+b

array([5, 7, 9])

In [91]:
a+c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [92]:
a-b

array([-3, -3, -3])

In [93]:
a*b

array([ 4, 10, 18])

In [94]:
a/b

array([0.25, 0.4 , 0.5 ])

In [95]:
a%b

array([1, 2, 3])

In [96]:
a<b

array([ True,  True,  True])

In [123]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [98]:
np.mean(a)

6.5

In [99]:
np.max(a)

12

In [100]:
np.min(a)

1

In [101]:
np.average(a)

6.5

In [102]:
np.sum(a)

78

In [104]:
len(a)

12

In [107]:
a.shape[0]

12

In [110]:
a=np.array([3,6,1,7,2,9])
a

array([3, 6, 1, 7, 2, 9])

In [111]:
np.sort(a)

array([1, 2, 3, 6, 7, 9])

In [112]:
a

array([3, 6, 1, 7, 2, 9])

In [113]:
a.sort()

In [114]:
a

array([1, 2, 3, 6, 7, 9])

In [115]:
a=(1,2,3)
a

(1, 2, 3)

In [116]:
a[0]

1

In [117]:
type(a)

tuple

In [119]:
a[0]

1

In [120]:
a[1]

2

In [122]:
a[2]

3

In [125]:
a.shape[0]

12

In [ ]:
1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

In [126]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /Users/nikhilsanghi/Downloads/01_dsml-course-main-live/batches/2_Aug_Beg_Tue_Feb_Inter_Feb_Adv_Oct_Inter/02_Numpy_2/survey.txt
100%|██████████████████████████████████████| 2.55k/2.55k [00:00<00:00, 2.90MB/s]


In [127]:
score=np.loadtxt("/Users/nikhilsanghi/Downloads/01_dsml-course-main-live/batches/2_Aug_Beg_Tue_Feb_Inter_Feb_Adv_Oct_Inter/02_Numpy_2/survey.txt",dtype="int")
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [128]:
# nps= %promotors -%detractors
# promotors ( 9, 10)
# detractor ( 0,6)
# passive ( 7,8)
# %promotors= (number of promotors/total number of surveyed customers)

In [131]:
total=score.shape[0]
total

1167

In [132]:
np.max(score)

10

In [133]:
np.min(score)

1

In [138]:
detractors=score[score<7].shape[0]
detractors

332

In [142]:
promotors=score[score>8].shape[0]
promotors

609

In [143]:
perc_promotors=promotors/total
perc_detractors=detractors/total

In [144]:
perc_promotors

0.5218508997429306

In [145]:
perc_detractors

0.28449014567266495

In [147]:
nps= (perc_promotors-perc_detractors)*100
nps

23.73607540702657

In [148]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

1 (8,)


In [ ]:

8 (8, )

In [ ]:

1 (1, )

In [ ]:
2 (2, )

In [ ]:
1 (8, )


In [150]:
a = np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [151]:
a[4:]

array([4, 5])

In [152]:
a[4:] = 10

In [153]:
a

array([ 0,  1,  2,  3, 10, 10])

In [ ]:
[0,1,2,3,4,5]

In [ ]:

[0,1,2,3,10,10]

In [ ]:
[0,1,2,3,10,5]

In [ ]:

Error

In [154]:
a = np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [155]:
mask = (a%2 == 0)


In [156]:
a[mask]

array([0, 2, 4])

In [ ]:
a[mask] = -1

In [ ]:

[0,1,2,3,4,5]


In [ ]:

[-1,1,-1,1,-1,1]

In [ ]:
Error

In [ ]:
[-1,1,-1,3,-1,5]

In [157]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [158]:
b = np.array([8,7,6])
b

array([8, 7, 6])

In [ ]:
a[2:]

In [ ]:
b[::-1]

In [159]:
a[2:] = b[::-1]

In [160]:
a

array([1, 2, 6, 7, 8])

In [ ]:
Error

In [ ]:
[1,2,6,7,8]

In [ ]:

[1,2,8,7,6]

In [ ]:

[1,2,8,7,6]

In [ ]:

[1,2,3,4,5,8,7,6]

In [174]:
a=np.array([[1,2,3,90],[4,5,6,90],[7,8,9,90],[10,11,12,90],[10,11,12,90]])
a

array([[ 1,  2,  3, 90],
       [ 4,  5,  6, 90],
       [ 7,  8,  9, 90],
       [10, 11, 12, 90],
       [10, 11, 12, 90]])

In [170]:
a.ndim

2

In [171]:
a.shape

(5, 4)

In [172]:
a.size

20